# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'editprofile.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1091, 558)
        self.graphicsView = QtWidgets.QGraphicsView(Dialog)
        self.graphicsView.setGeometry(QtCore.QRect(-85, -99, 1351, 161))
        self.graphicsView.setObjectName("graphicsView")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(60, 10, 151, 61))
        self.label.setStyleSheet("image: url(:/newPrefix/logo.png);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.graphicsView_2 = QtWidgets.QGraphicsView(Dialog)
        self.graphicsView_2.setGeometry(QtCore.QRect(420, 90, 261, 431))
        self.graphicsView_2.setObjectName("graphicsView_2")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(430, 99, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.line = QtWidgets.QFrame(Dialog)
        self.line.setGeometry(QtCore.QRect(420, 120, 261, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(430, 140, 121, 20))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(430, 170, 91, 20))
        self.label_4.setObjectName("label_4")
        self.firstnameinput = QtWidgets.QLineEdit(Dialog)
        self.firstnameinput.setGeometry(QtCore.QRect(440, 190, 231, 31))
        self.firstnameinput.setObjectName("firstnameinput")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(430, 240, 91, 20))
        self.label_5.setObjectName("label_5")
        self.lastnameinput = QtWidgets.QLineEdit(Dialog)
        self.lastnameinput.setGeometry(QtCore.QRect(440, 260, 231, 31))
        self.lastnameinput.setObjectName("lastnameinput")
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(430, 310, 91, 20))
        self.label_6.setObjectName("label_6")
        self.emailinput = QtWidgets.QLineEdit(Dialog)
        self.emailinput.setGeometry(QtCore.QRect(440, 330, 231, 31))
        self.emailinput.setObjectName("emailinput")
        self.label_7 = QtWidgets.QLabel(Dialog)
        self.label_7.setGeometry(QtCore.QRect(430, 380, 91, 20))
        self.label_7.setObjectName("label_7")
        self.passwordinput = QtWidgets.QLineEdit(Dialog)
        self.passwordinput.setGeometry(QtCore.QRect(440, 400, 231, 31))
        self.passwordinput.setObjectName("passwordinput")
        self.savebutton = QtWidgets.QPushButton(Dialog)
        self.savebutton.setGeometry(QtCore.QRect(574, 450, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.savebutton.setFont(font)
        self.savebutton.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 85, 255);")
        self.savebutton.setObjectName("savebutton")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_2.setText(_translate("Dialog", "  Edit Info"))
        self.label_3.setText(_translate("Dialog", "* Indicates Required"))
        self.label_4.setText(_translate("Dialog", "*  First Name:"))
        self.label_5.setText(_translate("Dialog", "*  Last Name:"))
        self.label_6.setText(_translate("Dialog", "*  Email:"))
        self.label_7.setText(_translate("Dialog", "*  Password:"))
        self.savebutton.setText(_translate("Dialog", "Save"))
import logo_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
