# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainpage.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1087, 559)
        Dialog.setStyleSheet("")
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.scrollArea = QtWidgets.QScrollArea(Dialog)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 1050, 1218))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.frame.setMinimumSize(QtCore.QSize(100, 1200))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.graphicsView = QtWidgets.QGraphicsView(self.frame)
        self.graphicsView.setGeometry(QtCore.QRect(-195, -89, 1361, 141))
        self.graphicsView.setObjectName("graphicsView")
        self.searchbar = QtWidgets.QLineEdit(self.frame)
        self.searchbar.setGeometry(QtCore.QRect(110, 10, 221, 31))
        self.searchbar.setObjectName("searchbar")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(10, -5, 71, 61))
        self.label.setStyleSheet("image: url(:/newPrefix/homelinkedin.jpg);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.networklabel = QtWidgets.QLabel(self.frame)
        self.networklabel.setGeometry(QtCore.QRect(550, 0, 81, 51))
        self.networklabel.setStyleSheet("image: url(:/newPrefix/networkpic.jpg);")
        self.networklabel.setText("")
        self.networklabel.setObjectName("networklabel")
        self.messaginglabel = QtWidgets.QLabel(self.frame)
        self.messaginglabel.setGeometry(QtCore.QRect(700, 0, 91, 51))
        self.messaginglabel.setStyleSheet("image: url(:/newPrefix/messagepic.jpg);")
        self.messaginglabel.setText("")
        self.messaginglabel.setObjectName("messaginglabel")
        self.profilelabel = QtWidgets.QLabel(self.frame)
        self.profilelabel.setGeometry(QtCore.QRect(830, 0, 101, 51))
        self.profilelabel.setStyleSheet("image: url(:/newPrefix/profilepic.jpg);")
        self.profilelabel.setText("")
        self.profilelabel.setObjectName("profilelabel")
        self.graphicsView_2 = QtWidgets.QGraphicsView(self.frame)
        self.graphicsView_2.setGeometry(QtCore.QRect(235, 70, 561, 71))
        self.graphicsView_2.setObjectName("graphicsView_2")
        self.label_6 = QtWidgets.QLabel(self.frame)
        self.label_6.setGeometry(QtCore.QRect(256, 82, 61, 51))
        self.label_6.setStyleSheet("image: url(:/newPrefix/profilepicforpost.png);")
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.startpostlabel = QtWidgets.QLabel(self.frame)
        self.startpostlabel.setGeometry(QtCore.QRect(320, 80, 431, 51))
        self.startpostlabel.setStyleSheet("image: url(:/newPrefix/startpost.jpg);")
        self.startpostlabel.setText("")
        self.startpostlabel.setObjectName("startpostlabel")
        self.label_8 = QtWidgets.QLabel(self.frame)
        self.label_8.setGeometry(QtCore.QRect(770, 150, 251, 301))
        self.label_8.setStyleSheet("image: url(:/newPrefix/extrapic.jpg);")
        self.label_8.setText("")
        self.label_8.setObjectName("label_8")
        self.graphicsView_3 = QtWidgets.QGraphicsView(self.frame)
        self.graphicsView_3.setGeometry(QtCore.QRect(50, 100, 141, 281))
        self.graphicsView_3.setObjectName("graphicsView_3")
        self.line = QtWidgets.QFrame(self.frame)
        self.line.setGeometry(QtCore.QRect(50, 150, 141, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.label_9 = QtWidgets.QLabel(self.frame)
        self.label_9.setGeometry(QtCore.QRect(76, 112, 81, 61))
        self.label_9.setStyleSheet("image: url(:/newPrefix/profilepic.jpg);")
        self.label_9.setText("")
        self.label_9.setObjectName("label_9")
        self.profilebutton = QtWidgets.QLabel(self.frame)
        self.profilebutton.setGeometry(QtCore.QRect(50, 180, 131, 41))
        self.profilebutton.setObjectName("profilebutton")
        self.line_2 = QtWidgets.QFrame(self.frame)
        self.line_2.setGeometry(QtCore.QRect(50, 310, 141, 20))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.discoverlabel = QtWidgets.QLabel(self.frame)
        self.discoverlabel.setGeometry(QtCore.QRect(50, 320, 141, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.discoverlabel.setFont(font)
        self.discoverlabel.setObjectName("discoverlabel")
        self.line_3 = QtWidgets.QFrame(self.frame)
        self.line_3.setGeometry(QtCore.QRect(60, 220, 118, 3))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(430, 0, 81, 51))
        self.label_2.setStyleSheet("image: url(:/newPrefix/homepic.jpg);")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.frame)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.searchbar.setPlaceholderText(_translate("Dialog", "   Search"))
        self.profilebutton.setText(_translate("Dialog", "     TextLabel"))
        self.discoverlabel.setText(_translate("Dialog", "  Discover More"))
import extrapic_rc
import homelinkedin_rc
import homepic_rc
import messagepic_rc
import networkpic_rc
import profilepic_rc
import profilepicforpost_rc
import startpost_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
