# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'searchprofile.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1091, 562)
        self.graphicsView = QtWidgets.QGraphicsView(Dialog)
        self.graphicsView.setGeometry(QtCore.QRect(-105, 0, 1361, 71))
        self.graphicsView.setObjectName("graphicsView")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(70, 10, 161, 71))
        self.label.setStyleSheet("image: url(:/newPrefix/logo.png);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.graphicsView_2 = QtWidgets.QGraphicsView(Dialog)
        self.graphicsView_2.setGeometry(QtCore.QRect(440, 120, 221, 361))
        self.graphicsView_2.setObjectName("graphicsView_2")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(456, 140, 61, 20))
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.namelabl = QtWidgets.QLabel(Dialog)
        self.namelabl.setGeometry(QtCore.QRect(466, 169, 161, 31))
        self.namelabl.setObjectName("namelabl")
        self.line = QtWidgets.QFrame(Dialog)
        self.line.setGeometry(QtCore.QRect(460, 190, 161, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.emaillabel = QtWidgets.QLabel(Dialog)
        self.emaillabel.setGeometry(QtCore.QRect(460, 230, 161, 31))
        self.emaillabel.setObjectName("emaillabel")
        self.line_2 = QtWidgets.QFrame(Dialog)
        self.line_2.setGeometry(QtCore.QRect(460, 250, 161, 20))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.connectbutoon = QtWidgets.QPushButton(Dialog)
        self.connectbutoon.setGeometry(QtCore.QRect(560, 320, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.connectbutoon.setFont(font)
        self.connectbutoon.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 85, 255);")
        self.connectbutoon.setObjectName("connectbutoon")
        self.messagebutton = QtWidgets.QPushButton(Dialog)
        self.messagebutton.setGeometry(QtCore.QRect(450, 320, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.messagebutton.setFont(font)
        self.messagebutton.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 85, 255);")
        self.messagebutton.setObjectName("messagebutton")
        self.previousbutton = QtWidgets.QPushButton(Dialog)
        self.previousbutton.setGeometry(QtCore.QRect(510, 380, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.previousbutton.setFont(font)
        self.previousbutton.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 85, 255);")
        self.previousbutton.setObjectName("previousbutton")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.namelabl.setText(_translate("Dialog", "TextLabel"))
        self.emaillabel.setText(_translate("Dialog", "TextLabel"))
        self.connectbutoon.setText(_translate("Dialog", "Connect"))
        self.messagebutton.setText(_translate("Dialog", "Message"))
        self.previousbutton.setText(_translate("Dialog", "Previous"))
import logo_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
