# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'start.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1077, 571)
        Dialog.setStyleSheet("background-color: rgb(0, 0, 108);")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(66, 62, 421, 351))
        self.label.setStyleSheet("image: url(:/newPrefix/logolinkedin.jpg);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.signinbutton = QtWidgets.QPushButton(Dialog)
        self.signinbutton.setGeometry(QtCore.QRect(590, 220, 151, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.signinbutton.setFont(font)
        self.signinbutton.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 134);")
        self.signinbutton.setObjectName("signinbutton")
        self.signupbutton = QtWidgets.QPushButton(Dialog)
        self.signupbutton.setGeometry(QtCore.QRect(800, 220, 151, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.signupbutton.setFont(font)
        self.signupbutton.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 134);")
        self.signupbutton.setObjectName("signupbutton")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.signinbutton.setText(_translate("Dialog", "Sign In"))
        self.signupbutton.setText(_translate("Dialog", "Sign Up"))



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
